### ISSUE TITLE
alt argümanın harita ekranındayken eklenmesi

### ISSUE THREAD

**Issue by mstdokumaci** [arguman/arguman.org#101]
alt argüman eklerken haritanın tamamının görünür olmadığı başka bir ekrana geçmek yazar açısından zorlayıcı olmaktadır.
- çünkü ekran değiştikten sonra hangi argümanın neye karşı yazıldığı ve benzer bir argümanın haritada zaten yer alıp almadığı kolaylıkla unutulmaktadır.
- ancak bu problem; alt argüman ekleme kutusunu, eklendikten sonra çıkacağı yerde açarak kolaylıkla çözülebilir.

**Comment by bbilginn** [comment]
Tıklatınca `/BASLIK/premises/ID/new` sayfasına değilde altta bir kutucuk olsa oradan girsek gibi :smile: 

---
![image](https://cloud.githubusercontent.com/assets/2061337/7393555/2d6b945c-ee97-11e4-899f-38fa54717c20.png)

**Comment by bahattincinic** [comment]
Api onerme eklemeye musayit. Bir popup yapsak olabilir aslinda.

**Comment by bbilginn** [comment]
@bahattincinic popup dan ziyade, hemen oracıkta olması daha kullanışlı olur ki.
