### ISSUE TITLE
[Öneri] SSL sorunu ve "şifre - parola" hatası

### ISSUE THREAD

**Issue by barisb** [arguman/arguman.org#105]
SSL her durumda [önemli](https://httpskullan.org/) olmaka birlikte bu tip; kullanıcının girdi oluşturduğu, sisteme login olduğu platformlarda daha da önemli. O nedenle (self-signed veya değil) bir SSL sertifikası olsa çok iyi olur. 

Bununla birlikte "**login**" ve "**register**" sayfalarında sıkça yapılan bir hata üzerine "**parola**" yerine "**şifre**" denmiş. Bilindiği üzere ikisi farklı şeyler ama durum sadece bir kelime hatası ile kalmıyor. Çünkü daha sonra bu ayrım anlaşılmakta güçlük çekiyor ve anlamanın önemli olduğu çok nokta var. Bu yanlış algıya katkıda bulunmak istemeyeceğinizi düşündüğümden yazayım dedim.

**Comment by ustun** [comment]
> Bununla birlikte "login" ve "register" sayfalarında sıkça yapılan bir hata üzerine "parola" yerine "şifre" denmiş. Bilindiği üzere ikisi farklı şeyler ama durum sadece bir kelime hatası ile kalmıyor. Çünkü daha sonra bu ayrım anlaşılmakta güçlük çekiyor ve anlamanın önemli olduğu çok nokta var. Bu yanlış algıya katkıda bulunmak istemeyeceğinizi düşündüğümden yazayım dedim.

Sifre sanirim galat-i meshur, facebook, gmail, eksisozluk hep bunu kullaniyor, bu nedenle bu sekilde kalmasi daha mantikli

**Comment by grotiiy** [comment]
ssl icin cloudflare'in ucretsiz paketi kullanilabilir, hem baska islere de yarar.

**Comment by EmiXLabs** [comment]
Malesef bu kullanılamaz, cloudflare bu zaman bilgileri sizin siteye açık göndericek, böylece ssl-in bir anlamı kalmayacak.

**Comment by halilkaya** [comment]
> Sifre sanirim galat-i meshur, facebook, gmail, eksisozluk hep bunu kullaniyor, bu nedenle bu sekilde > kalmasi daha mantikli

Bence onlarin da kullanmasi mantikli degil. Dogru kullanim neyse onu yapalim derim ben.

**Comment by ustun** [comment]
Yeni fark ettim, Apple parola kullanıyor, aferin, yine farkını göstermiş :)

**Comment by kseistrup** [comment]
I can't read turkish but I assume this issue is about the missing TLS/SSL when signing up or logging in (heck, the whole thing should be encrypted, not just the sign up/in pages).

This issue is pretty old.  Please consider getting a certificate from [Let's Encrypt](https://letsencrypt.org/) or similar.  Or raise some fonds and buy a certificate.  Argüman seems to be a nice platform but I'm not gonna expose my password over an insecure wire.
