### ISSUE TITLE
Takip et butonu - Giriş yönlendirmesi

### ISSUE THREAD

**Issue by 0x90kh4n** [arguman/arguman.org#109]
Ziyaretçi sitede login değilse görüntülediği profil sayfasında ki takip et butonu giriş sayfasına yönlendirilebilir.

http://arguman.org/login/?continue=http://arguman.org/users/0x90kh4n

**Comment by hmert** [comment]
bd5a9157d237a0eea9e73e5d5130d3d211e0bb9a
