### ISSUE TITLE
'Last time' dilleri

### ISSUE THREAD

**Issue by livacengiz** [arguman/arguman.org#119]
Bazı argümanlarda ingilizce bazı argümanlarda türkçe oluyor. 
![screen shot 2014-11-15 at 5 59 52 pm](https://cloud.githubusercontent.com/assets/6208736/5058262/456db6e8-6cf1-11e4-90a9-a69786831b0b.png)

**Comment by halilkaya** [comment]
Bu bug devam etmiyor sanirim?

**Comment by livacengiz** [comment]
fix.
