### ISSUE TITLE
Kendi eklediğimiz argüman'a girilen argümanları (ama,ancak,çünkü) destekleyemiyoruz? Veya ben mi görmedim?

### ISSUE THREAD

**Issue by smtaydemir** [arguman/arguman.org#126]
![ekran resmi 2014-11-20 17 46 30](https://cloud.githubusercontent.com/assets/4273973/5127491/32e20bc4-70dd-11e4-93cf-9e91c92b98e0.png)

**Comment by bahattincinic** [comment]
@hmert pr gondermistim bu bug cozuldu mu ?

**Comment by hmert** [comment]
prod ortamındakinde test edemedim ancak benim tarafta düzelmiş.
