### ISSUE TITLE
Yapılmakta olan işler hakkında

### ISSUE THREAD

**Issue by hmert** [arguman/arguman.org#150]
@fatiherikli @bahattincinic aldığınız/yapmaya başladığınız işe #WIP ekleyin

**Comment by bahattincinic** [comment]
ben ekleyemiyorum. yetkim yok galiba.

**Comment by hmert** [comment]
@fatiherikli bize şuanda planladığın işlerden bahsedebilir misin?

**Comment by bahattincinic** [comment]
Ben surda i18n e basladim.
https://github.com/bahattincinic/arguman.org/compare/i18n
destek olmak isteyen varsa direk commit yapabilir. Cevirilicek cok sey var :sweat_smile:

**Comment by hmert** [comment]
@bahattincinic sen commit olarak yolla bunu. Ben yaparım oradaki amelliği.

@fatiherikli ses 1 2 3

**Comment by bahattincinic** [comment]
@hmert  https://github.com/arguman/arguman.org/tree/i18n yolladim.

**Comment by hmert** [comment]
harika, eline saglik

**Comment by bahattincinic** [comment]
Bazi yerleri cok guzel olmadi oralari duzelticem merge olmadan.

**Comment by bahattincinic** [comment]
Translation icin https://www.transifex.com bunu kullanabiliriz aslinda. Herkesin bi katkisi olur.

**Comment by fatiherikli** [comment]
@hmert ben API ile ilgilenecegim android client icin.
@halilkaya ve @caglarbozkurt android app'i gelistiriyorlar.

**Comment by hmert** [comment]
@fatiherikli Allah razı olsun, teşekkür ederim.
