### ISSUE TITLE
Neden anonim kalarak argüman sunamıyoruz?

### ISSUE THREAD

**Issue by miratcan** [arguman/arguman.org#151]

**Comment by hmert** [comment]
Bunu düşünmekle beraber fikrinizi anonim savunmak zor olmayacak mı?

**Comment by miratcan** [comment]
Zorluğu nerede?

**Comment by nejdetckenobi** [comment]
neden anonim sunmak istiyorsunuz mesela?

**Comment by hmert** [comment]
Anonim olarak gittiğinde mutlaka bir moderasyondan sunulması gerekiyor. Bu durumda kişinin kim olduğunun kontrol edilmesi gerekiyor. 

Ayrıca fikrin anonim olarak sunulmasını garip buluyorum, fikrimi ben şahsımı gizleyerek savunamayacaksam nasıl bir dünyada yaşıyorum diye sorgularım.

**Comment by nejdetckenobi** [comment]
hmert +1
ayrıca, username yeterli düzeyde anonimlik sağlıyor zaten.

**Comment by hmert** [comment]
ayrıca kişilik veya marka haklarını zedeleyen bir durumda sorumlu olarak arguman.org'un olmaması gerekli. Anonim bir şekilde yapılacak bu şeylerde moderasyona tabi tuttuğumuzda platform olarak sansürcü durumuna düşmüş olmuş oluruz. Platformun bu konularda zor durumda kalmaması gerekli.

**Comment by miratcan** [comment]
Örnek vaka olarak bugün "Sekülerlerin de kendini silaha savunma hakkı vardır." yazacaktım vazgeçtim. Zira twitter hesaplarımızdan ötürü bile terörist ilan edilebilir bir ülkedeyiz.

**Comment by hmert** [comment]
Argüman'ın arkasındakilerin zor durumda kalmasını tercih edebilirsiniz. Biz de arguman.org olarak elimizden geldiği kadar kimsenin zor durumda kalmamasını tercih ediyoruz. :angel: 

Anonim olarak argüman gönderilmesi mümkün görünmüyor.
