### ISSUE TITLE
API Safsatalar ve destekleyenler eksik

### ISSUE THREAD

**Issue by halilkaya** [arguman/arguman.org#159]

**Comment by bahattincinic** [comment]
Suan safsata olarak ekleyebiliyorsun ve destekleyebiliyorsun.

**Safata olarak eklemek:**
curl -X POST  -H "Authorization: Token 173f758803eb1fb0ffaf36a782caaa885bd42af2"
              http://localhost:8000/api/v1/premises/1/report/

**Desteklemek:**
curl -X POST  -H "Authorization: Token 173f758803eb1fb0ffaf36a782caaa885bd42af2"
              http://localhost:8000/api/v1/premises/1/support/

**Desteklemeyi Geri almak:**
curl -X DELETE  -H "Authorization: Token 173f758803eb1fb0ffaf36a782caaa885bd42af2"
              http://localhost:8000/api/v1/premises/1/support/


Destekleyenlerin kullanicilarin listesini eklememisim. Ekliyim mi @halilkaya

**Comment by bahattincinic** [comment]
#162 ile merge oldu. PR icinden kullanimlarini ufak bir domuman olarak yazdim. Bakabilirsin
