### ISSUE TITLE
Aramanın ElasticSearch'e taşınması

### ISSUE THREAD

**Issue by bahattincinic** [arguman/arguman.org#175]

**Comment by miratcan** [comment]
Bu işi django-watson ilginç bir şekilde güzelce çözüyor, elasticsearch'e falan gerek kalmayabilir.

**Comment by bahattincinic** [comment]
Buda veritabanina yaziyor galiba. Benim aslinda elasticsearch e koyalim deme sebebim daha sonra arguman icinde benzer argumanlar vs. gibi widgetler dede oraya query atip kullanabiliriz diye dedim.

**Comment by halilkaya** [comment]
Ne durumda bu issue? Eger karar verilirse ben de yardimci olabilirim @bahattincinic

**Comment by bahattincinic** [comment]
@halilkaya Henuz baslayamadim. Su birkac aydir inanilmaz yogunum kivilcim cikaricam :smile: 
Sen basla istersen Base inin cikart sonrasinda bende bir seyer eklerim ne dersin ?
