### ISSUE TITLE
Argümanların detay sayfasında "çünkü, ama, ancak" lar için bir gösterge olabilir.

### ISSUE THREAD

**Issue by bbilginn** [arguman/arguman.org#178]
#### Şuna benzer.

---

![image](https://cloud.githubusercontent.com/assets/2061337/7393406/32d0c530-ee96-11e4-8245-940ec9a103ea.png)

**Comment by livacengiz** [comment]
Guzel olabilir. Ama sadece ana onermelerin istastigini cikarmak mantikli geliyor. Diger turlu ana onermeye "ama" girilmis ve  bu onermeye daha sonra "cunku" seklinde bir onerme daha girilmisse istatistik verisinde bozukluk yasanabilir. Toplu istatistik biraz anlamsiz geliyor. 

![screen shot 2015-05-02 at 03 02 25](https://cloud.githubusercontent.com/assets/6208736/7439051/f51cfba8-f077-11e4-8473-f0a0d64f0cc5.png)

**Comment by bbilginn** [comment]
@livacengiz aynen, katılıyorum. Şimdilik sadece ilk sıra için olabilir. 
Onun dışında kalanlar için de bir formül bulunabilir sanki. Düşünmek lazım biraz.
