### ISSUE TITLE
Kurulumda hata

### ISSUE THREAD

**Issue by muratbastas** [arguman/arguman.org#181]
Kurulum aşamasında requirements.pip dosyasını çalıştırırken şu syntax hatasını alıyorum.
> File "/private/var/folders/07/tq53_7_91jl0256v6yv_kct40000gn/T/pip-build-fq6vg8_5/oauth2/setup.py", line 18 print "unable to find version in %s" % (VERSIONFILE,)
> Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/07/tq53_7_91jl0256v6yv_kct40000gn/T/pip-build-8foyuyyy/oauth2

**Comment by fatiherikli** [comment]
Requirements dosyasını güncelledim. Tekrar deneyebilir misiniz?

**Comment by muratbastas** [comment]
Şimdi de şöyle bir problem çıktı, osx yosemite ile alakalı sanırım.
> Could not find a version that satisfies the requirement oauth2==1.5 (from -r arguman.org/requirements.pip (line 5)) (from versions: 1.0.6.macosx-10.6-universal, 1.0.0, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.1.0, 1.1.1, 1.1.3, 1.2.0, 1.5.150, 1.5.153, 1.5.155, 1.5.158, 1.5.159, 1.5.160, 1.5.161, 1.5.162, 1.5.163, 1.5.164, 1.5.165, 1.5.166, 1.5.167, 1.5.168, 1.5.169, 1.5.170, 1.5.210, 1.5.211)
>  Some externally hosted files were ignored as access to them may be unreliable (use --allow-external oauth2 to allow).
> No matching distribution found for oauth2==1.5 (from -r arguman.org/requirements.pip (line 5))

**Comment by fatiherikli** [comment]
`pip install oauth2` diyerek o paketi kendin kurmayı deneyebilir misin?

**Comment by muratbastas** [comment]
Root erişimi ile 'pip install oauth2' diyerek kendim kurdum. Repoyu da güncelleyerek tekrar requirements.pip dosyasını kurmayı denerken aynı hatayı tekrar alıyorum.

**Comment by fatiherikli** [comment]
Virtualenv kurulumu yaptın mı?

**Comment by muratbastas** [comment]
Evet hocam virtualenv kurulu, `source argumanorg/bin/activate` dedim ve sonra repoyu klonladım. Atladığım bir adım mı var acaba?

**Comment by muratbastas** [comment]
Çözüldü. requirements.pip dosyasında oauth2 versiyon bilgisini güncelleyip kurulumu denediğimde çalıştı. Teşekkürler @fatiherikli 
> oauth2==1.5.211
