### ISSUE TITLE
Şifre değiştirme & hesap ayarları

### ISSUE THREAD

**Issue by hulooo** [arguman/arguman.org#20]
Ben mi göremedim, yoksa henüz yok mu bu özellikler?

**Comment by fg** [comment]
@bahattincinic #114 çözülmüş bu durum sanki?

**Comment by bahattincinic** [comment]
@fg Sifremi unuttum henuz yok. (Benum uzerimde is.)  o is bitince kapatilicak galiba.

**Comment by hmert** [comment]
(KAPANMADI)

**Comment by bahattincinic** [comment]
@hmert bu iste baska ne eksik. Varsa ben yapiyim

**Comment by hmert** [comment]
#70 var, onun sonrasında api var.

**Comment by bahattincinic** [comment]
#70 i yaptim ben merge oldu

Apiyi bu haftasonuna engec yollarim :smile:

**Comment by hmert** [comment]
teşekkürler, farketmedim
(YOLLAYAMADI)

**Comment by bahattincinic** [comment]
Aslinda yaptimda daha guzel bir yontem aklima geldi oyle tekrardan denicem :smile:

**Comment by hmert** [comment]
*-da* ayrı

**Comment by bahattincinic** [comment]
:sweat_smile:
