### ISSUE TITLE
Great idea, but navigation is a pain.

### ISSUE THREAD

**Issue by jbnv** [arguman/arguman.org#201]
If there is a way to collapse the tree/list to focus on a particular branch, it is not readily apparent. Even small discussion trees are hard to navigate. Also, when I click on Support, the page refreshes, moving me away from the part of the tree that I was working on.

**Comment by kdsch** [comment]
Agreed, the navigation is simplistic. There are probably several ways it could be improved. The following ideas occurred to me:

1. Don't allow continuous panning of the view. Always center the view on a particular branch. This would help in scanning through an argument. it would also help to linearize the display of the chosen branch, to ease reading.
2. A related but separate feature would adapt the display of the tree to maximize the use of screen space, avoiding large blank areas. This would be useful especially for navigating parallel branches, deciding which one to visit next.
