### ISSUE TITLE
blog kısmındaki resimler

### ISSUE THREAD

**Issue by mtalhasahin** [arguman/arguman.org#204]
Blog Kısmında ki resimler gözükmüyor bilginize..
İyi çalışmalar dilerim

**Comment by bahattincinic** [comment]
Blog kısmındaki resimler imgurdan çekildiği için gözükmüyor. İmgur Devlet tarafından engellendiği için DNS veya VPN kullanmayanlarda gözükmüyor. Onları değiştirmek lazım :smile:

**Comment by mtalhasahin** [comment]
tamamdır :+1:
