### ISSUE TITLE
Running without Vagrant

### ISSUE THREAD

**Issue by Fastidious** [arguman/arguman.org#214]
How to get this running without Vagrant? Are the instructions somewhere that misses the eye?

**Comment by fatiherikli** [comment]
There is a document for installation, but it is not translated yet. 

https://github.com/arguman/arguman.org/blob/master/docs/installation.md

**Comment by ivangretsky** [comment]
Cool! If I knew turkish, I could help) Plese consider making a translation if you find some time. Your product is worth being known by many.

**Comment by fatiherikli** [comment]
It will be translated soon as soon.
