### ISSUE TITLE
MongoDB AND Redis

### ISSUE THREAD

**Issue by EHadoux** [arguman/arguman.org#228]
In the installation guide, we can see we need both MongoDB and Redis.
Why do we need both of them?

**Comment by jorgebg** [comment]
MongoDB is used for model persistence, and Redis is most likely to be used
as a cache in production.

On Wed, Oct 21, 2015 at 1:47 PM, Emmanuel Hadoux <notifications@github.com>
wrote:

> In the installation guide, we can see we need both MongoDB and Redis.
> Why do we need both of them?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arguman/arguman.org/issues/228>.
>



-- 
Jorge

**Comment by EHadoux** [comment]
Ok so as of today, are they both used? I mean, in the settings.py, Redis is commented out and MongoDB is not even there, that is SQLite inside.
I am just trying to figure out how to break the monolith.

**Comment by fatiherikli** [comment]
Redis is not necessary for development. It is using for cache.

**Comment by jorgebg** [comment]
You can use Redis defining the cache in `settings_local.py`.
I don't know which file settings are you looking into, but in the master tree [MongoDB is already set](https://github.com/arguman/arguman.org/blob/master/web/main/settings.py#L216-L217) and [used](https://github.com/arguman/arguman.org/blob/master/web/newsfeed/models.py).

Why do you want to _break the monolith_?

**Comment by EHadoux** [comment]
My bad, I was looking at [this](https://github.com/arguman/arguman.org/blob/master/web/main/settings.py#L77-L82).
I am not a Django expert by any means.

I am working in the argumentation field of AI and I would like to propose arguman as some kind of reference platform for this domain.
However, most people are not webdev nor Python experts and I find it difficult to dive into to modify models, add algorithms, etc. as the business logic and the web part are tightly coupled (see #227).

**Comment by KrzysztofMadejski** [comment]
Why do you need both Mongo and PgSQL?
