### ISSUE TITLE
url formation 

### ISSUE THREAD

**Issue by sgt101** [arguman/arguman.org#232]
Hello - I've cloned arguman and am running it on an ubuntu box. 

When I run "python manage.py runserver" I can access localhost:8000 in my browser and a message for the http get appears in the console. 
However I am then redirected by the code in settings.py to the en.arguman.org server. 
I have edited BASE_DOMAIN to give the URL of my server, however this is forcing a URL of en.x.x.x.x which is no good for me as I am running on an intranet and my machine just has a IP address, not a DNS entry. 

How do I strip the en from the URL?

**Comment by fatiherikli** [comment]
You can set `PREVENT_LANGUAGE_REDIRECTION = True` in your settings_local.py

On 23 October 2015 at 19:34, sgt101 <notifications@github.com> wrote:

> Hello - I've cloned arguman and am running it on an ubuntu box.
>
> When I run "python manage.py runserver" I can access localhost:8000 in my
> browser and a message for the http get appears in the console.
> However I am then redirected by the code in settings.py to the
> en.arguman.org server.
> I have edited BASE_DOMAIN to give the URL of my server, however this is
> forcing a URL of en.x.x.x.x which is no good for me as I am running on an
> intranet and my machine just has a IP address, not a DNS entry.
>
> How do I strip the en from the URL?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arguman/arguman.org/issues/232>.
>



-- 
Fatih Erikli
http://www.fatiherikli.com

**Comment by sgt101** [comment]
Thanks - yes that works.
