### ISSUE TITLE
Sugesttion: Fallacy Link and Other sources

### ISSUE THREAD

**Issue by zehfernandes** [arguman/arguman.org#234]
Hey,

Some ideas to improve user read about some premise:
- The link in Fallacy list explains what is.
- Allow users link other sources to premise. (normally is just Wikipedia and that is bad)

**Comment by felixhummel** [comment]
:+1: 's are useless, so here's a link to Wikipedia: https://en.wikipedia.org/wiki/List_of_fallacies
A link to the fallacy would be nice.
A short tooltip (with Wikipedia's abstract) would be nice too.

**Comment by KrzysztofMadejski** [comment]
Are there links to Wikipedia? I don't see it..

I think that each FALACCY_TYPE (premises/models.py:45) should have a link to wikipedia and be translatable.
