### ISSUE TITLE
Cannot undo "fallacy"

### ISSUE THREAD

**Issue by jmmcgee** [arguman/arguman.org#236]
I was exploring the fallacy tagging feature, with no intent to publish the report... Of course I accidently published the report.  This is completely my fault.

However, it would be nice to have the ability to undo accidental changes such as mine.
Or short of that, you might prompt a warning and require the user to confirm their action when reporting an argument.

**Comment by jmmcgee** [comment]
I apologize. This concern has already been raised in #221.

**Comment by fatiherikli** [comment]
This is resolved now. 
https://github.com/arguman/arguman.org/issues/221#issuecomment-150980611
