### ISSUE TITLE
Creating announcements ? 

### ISSUE THREAD

**Issue by sgt101** [arguman/arguman.org#238]
Hi, 

I'd like to be able to make announcements on my internal server, but I can't get Mongo to do it! 

I've tried 

db.announcements.insert({tltle: "...."}) 
but nothing shows up on the ui. 

What's the magic? 

Also, how do I get something "featured" - what's the flag I have to set in the DB? 

Thanks!

**Comment by sgt101** [comment]
Also - just to check (pretty sure I know) all the data is stored in Mongo locally?

**Comment by fatiherikli** [comment]
Announcements are just blog posts with `is_announcement=True` option.

Only newsfeed is stored on mongodb, the rest of all is in your relational database.

**Comment by sgt101** [comment]
Thanks - I'm sure I am getting annoying now... but how do I create a blog post? I can't find any documentation for that...

**Comment by fatiherikli** [comment]
Admin panel :)

http://yourdomain/admin

On Wednesday, October 28, 2015, sgt101 <notifications@github.com> wrote:

> Thanks - I'm sure I am getting annoying now... but how do I create a blog
> post? I can't find any documentation for that...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arguman/arguman.org/issues/238#issuecomment-151881444>
> .
>


-- 
Fatih Erikli
http://www.fatiherikli.com
