### ISSUE TITLE
The new branch system is very disfunctional

### ISSUE THREAD

**Issue by gappleto97** [arguman/arguman.org#240]
It makes navigation much harder, rather than easier, and it reduces the amount of information we have available to us.

**Comment by fatiherikli** [comment]
We can add a button that expands/collapses the all branches, or what do you suggest instead?

**Comment by gappleto97** [comment]
I would suggest making that the default, and allowing to switch to the
compact view.

Or allowing us to set a fully expanded view as our personal default.

**Comment by fatiherikli** [comment]
We added this functionality for complex arguments. Maybe we can expanded all branches as default for arguments that below a certain number of premises

**Comment by gappleto97** [comment]
This seems like a fair balance. I would still appreciate a global toggle.

**Comment by gappleto97** [comment]
Just took a look. New balance seems very good. Perhaps default limit could be brought down to three branches instead of four. Argument-wide expand button still seems appropriate, but otherwise this is much better.
