### ISSUE TITLE
Cannot remove support on yellow issues

### ISSUE THREAD

**Issue by gappleto97** [arguman/arguman.org#241]
Green premise: ![](http://i.imgur.com/HNwRwbJ.png)

Yellow premise: ![](http://i.imgur.com/JhI3wWD.png)

Red premise: ![](http://i.imgur.com/UKmDgJF.png)

I supported each of these premises. I can only undo support for two of the three. This appears to be consistent across all premises.

**Comment by beratdogan** [comment]
It's valid for all premises.

Technical cause explation: DELETE request is not allowed.
