### ISSUE TITLE
API followers next problem

### ISSUE THREAD

**Issue by halilkaya** [arguman/arguman.org#244]
When fetching followers from API, next does not stop :) If it's even the last page, it gives the next link but returns 404. Ex.: http://arguman.org/api/v1/users/fatiherikli/followers/?page=5 gives followers on 5th page but http://arguman.org/api/v1/users/fatiherikli/followers/?page=6 is 404. @bahattincinic

**Comment by halilkaya** [comment]
It also happens on /arguments endpoint :(

**Comment by EHadoux** [comment]
I guess it happens on every endpoints :(

**Comment by fatiherikli** [comment]
Should be fixed now.

**Comment by EHadoux** [comment]
Sorry for that, it seems like. Yesterday I was getting html pages. Maybe a server problem.
Thanks anyway, I guess you can close the issue!

**Comment by fatiherikli** [comment]
HTTP 500 responding with html pages, and this is another problem, I'll fix that too.
