### ISSUE TITLE
Add "last updated" info at top of an argument's page

### ISSUE THREAD

**Issue by Korporal** [arguman/arguman.org#250]
When viewing an argument tree, it would be helpful to see a summary of who last added or changed anything and when. This way I can just refresh a page and see "Last updated by Socrates at 11:23:05 11/26/2015" for example - this is low hanging fruit!

**Comment by fatiherikli** [comment]
We are working a feature that resolves this problem, and even more. We will add a timeline bar above the argument tree.

**Comment by raindropsfromsky** [comment]
Hi

This feature is implemented now (Jan 2016). But when someone updates the argument map, the "last updated" time-stamp and user name are not updated at the top of the page (above the color-coded timeline).
