### ISSUE TITLE
Nötr destekleme ve itiraz oranında yüzdelik kısım yok

### ISSUE THREAD

**Issue by smtaydemir** [arguman/arguman.org#254]
![ekran resmi 2015-12-02 22 31 17](https://cloud.githubusercontent.com/assets/4273973/11543316/98d8a4ca-9944-11e5-8a7d-6a250be35bff.png)

**Comment by fatiherikli** [comment]
:shipit:

**Comment by fatiherikli** [comment]
Hiç önermesi olmayan ya da itiraz/destek oranı %50 olanlar nötr olarak gözüküyor. Hepsi %50 olarak gözükeceği için eklememiştim.

**Comment by smtaydemir** [comment]
fark etmemişim, kapatıyorum issue'yu
