### ISSUE TITLE
Feature Request / Contribution - Async video argumans

### ISSUE THREAD

**Issue by pseudozach** [arguman/arguman.org#257]
Selam,

I've been meaning to get around to launching a public debate website with webRTC support to enable asynchronous video debates. Since arguman.org is open source and amazing I was hoping you might be interested in such a thing. Let me know if you think this is a good idea/fit for arguman.org.

I'm happy to discuss or provide a quick demo if there's interest.

**Comment by hmert** [comment]
I'm in. That would be a good feature. What would you have in your mind?

**Comment by pseudozach** [comment]
Similar to arguman.org flow, users will pick a topic and a side (because vs. however vs. but) then they will record a video through the web app and it'll be placed it in the arguman tree. 
This feature can mix with the textual argumans or it can be a completely separate feature/page. 

I was imagining the same tree structure with thumbnails of videos so in the end you can have a auto-play switch and you can play a playlist of a public video debate.

Some issues to consider: video length might be limited to 3 minutes, some moderation will be required to check for video content.

**Comment by pseudozach** [comment]
here's a demo I whipped up, UI and logic is quiet different and I set the video record length to 10 seconds for starters.
https://lockandgo.cloudapp.net/
thanks for the inspiration.
