### ISSUE TITLE
It would be nice to have Ukrainian version of Arguman.

### ISSUE THREAD

**Issue by kirushyk** [arguman/arguman.org#259]
Hello, I almost translated .po file. I can polish it this week. Can you set up Ukrainian version?

**Comment by fatiherikli** [comment]
Can you create a pull request for you .po file?

We'll review and merge all i18n pull requests in this month.

**Comment by kirushyk** [comment]
Sure. Only .po file?

**Comment by fatiherikli** [comment]
Yes. We can setup the domain configuration.

On Monday, 4 January 2016, Kyrylo Polezhaiev <notifications@github.com>
wrote:

> Sure. Only .po file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arguman/arguman.org/issues/259#issuecomment-168757148>
> .
>


-- 
Fatih Erikli
http://www.fatiherikli.com

**Comment by kirushyk** [comment]
Okay, there are few places where I am still unsure :-)

**Comment by kirushyk** [comment]
Oh, still not finished...

**Comment by KrzysztofMadejski** [comment]
Hi @kirushyk, how is it going? I plan to add Polish version (just encouraging your efforts). :)
