### ISSUE TITLE
Branches do not kern

### ISSUE THREAD

**Issue by gappleto97** [arguman/arguman.org#262]
Kerning is probably not the right word, but it's the closest I can find.  Basic idea: branches should go as close as possible without overlapping.

Example: This is the current view.

![](https://i.imgur.com/gYfENMC.png)

If you were to add kerning to the dropdowns, it would look more like this:

![](https://i.imgur.com/AkkxZqb.png)

Much nicer looking if you ask me.

**Comment by fatiherikli** [comment]
I cannot see the difference :( What did you in second screenshot?

**Comment by gappleto97** [comment]
See how the two branches are closer together, with the right branches taking the space unused (though normally reserved) by the leftmost branches?

**Comment by gappleto97** [comment]
What I'm trying to say is this. When the page draws, it currently divides into columns. Each branch fills the entirety of a column.

Sometimes it doesn't take the full space of a column, though. So you get tables that look like:

x |  | y |  | z 
---|----|----|----|----
x1 |  | y1 | y2 | z1
x1.1 | x1.2 |  | y2.1 | z1.1

It would be better if those tables could be drawn like:

x | y |  | z 
----|----|----|----
x1 | y1 | y2 | z1
x1.1 | x1.2 | y2.1 | z1.1

**Comment by gappleto97** [comment]
That makes things much more aesthetically pleasing, and reduces the required screen real estate.
