### ISSUE TITLE
Fallacy notification not providing link to fallacious premise

### ISSUE THREAD

**Issue by gappleto97** [arguman/arguman.org#263]
It appears in `arguman.org/web/templates/notifications/reported-as-fallacy.html` that it should work, but on the notifications view this does not appear.

**Comment by gappleto97** [comment]
Possibly related to #264

**Comment by raindropsfromsky** [comment]
***Rephrased:***
When a user reports a fallacy, Arguman helps in selecting a fallacy by providing a link to [list of fallacies at Wikipedia](https://en.wikipedia.org/wiki/List_of_fallacies).

However, once a fallacy is selected, only its name appears in the map. If other users want to know what it means, there is no quick link to Wikipedia. 

Arguman should provide a direct link to the Wikipedia page for that particular fallacy; not to the list of fallacies. For example, if the user has pointed to ***Anecdotal fallacy***, it should link to [this page](https://en.wikipedia.org/wiki/Misleading_vividness)
