### ISSUE TITLE
Fetching most crowded all time using API

### ISSUE THREAD

**Issue by EHadoux** [arguman/arguman.org#266]
Hello,
it seems like we cannot fetch the debates listed here using the API: [http://en.arguman.org/stats?what=crowded_contentions&days=all](http://en.arguman.org/stats?what=crowded_contentions&days=all).
Moreover, it might be useful to give the id of the debate somewhere in the page to be able to put the right number in the query.
Thanks!

**Comment by EHadoux** [comment]
Bumping, it's still not working. I would like to use your plateform for a paper but the deadline is getting very close.

**Comment by fatiherikli** [comment]
To clarify, you expecting a `stats` endpoint like this:

`http://arguman.org/api/v1/arguments/1/stats`

Right?

**Comment by EHadoux** [comment]
Not quite. I meant that the arguments listed in http://en.arguman.org/stats?what=crowded_contentions&days=all are not accessible nor even listed using the endpoint [http://arguman.org/api/v1/arguments/](http://arguman.org/api/v1/arguments/) (or at least were not, I did not test this week).

**Comment by fatiherikli** [comment]
I guess you want an endpoint which returns crowded arguments.

I'll add these endpoints:
http://arguman.org/api/v1/arguments/crowded_contentions

Is it okay?

**Comment by EHadoux** [comment]
Hello, 

Let's take an example.
Let's say I want to fetch the debate http://en.arguman.org/there-is-no-such-thing-as-global-warming.
I take the endpoint http://arguman.org/api/v1/arguments/ which is suppose to list all debates right? (running it with ?page= until the end)
From what I see, the debate about global warming never appears.

So I just want them to appear in the list, not to list them apart.
Moreover, I could be very useful to have the idea of the debate somewhere on the page, to be able to get it directly, with having to search for it.

Is it more clear?

Thank you very much

**Comment by fatiherikli** [comment]
Ah, okay.

I noticed that `there-is-no-such-thing-as-global-warming` is not a published argument. I fixed that, you should see now.

Here is the endpoint:
http://arguman.org/api/v1/arguments/1337/

**Comment by fatiherikli** [comment]
You could close the issue if you are okay.

**Comment by EHadoux** [comment]
Great, thank you. Is it the case for every argument of the most crowded list?
Moreover, if I fetch the endpoint http://arguman.org/api/v1/users/Mungabunga/owner/ (which is the owner of the ```there-is-no-such...```), it gives the error HTML page.

**Comment by fatiherikli** [comment]
Error with HTML page is a different case and error. I'll take a look at this
