### ISSUE TITLE
API date formatting

### ISSUE THREAD

**Issue by cekisakurek** [arguman/arguman.org#288]
Hello, 
I noticed there is a inconsistency between date formats in newsfeed endpoint and arguments endpoint.

in newsfeed the date format is yyyy-MM-dd'T'HH:mm:s.SSS
however,
in arguments it is dd-MM-yyyy HH:mm

Thanks.

**Comment by hmert** [comment]
@cekisakurek naber (orta okul arkadaşım) 🎉

**Comment by cekisakurek** [comment]
@hmert iyilik senden? :)

**Comment by hmert** [comment]
@cekisakurek nabak iyilik işte (şimdilik bu kadar kirlettiğimiz yeter 👍 )

**Comment by bahattincinic** [comment]
Hello Cihan,
We've served this endpoint with MongoDB. While making location this endpoint forgotten.
We'll fix it 👍 
Thanks.
