### ISSUE TITLE
add setup.py, add src/, rename main package web -> arguman

### ISSUE THREAD

**Issue by ThomasWaldmann** [arguman/arguman.org#297]
structure should be like

```
src/arguman/__init__.py
src/arguman/...
```

introducing the "src/" directory has a lot of benefits for testing (e.g. to make sure you are actually testing the stuff that gets installed, not the stuff that happens to be found in cwd).

**Comment by KrzysztofMadejski** [comment]
Package could be put then to `pip`. 
BTW: `Setup.py` should then list dependencies.

**Comment by ThomasWaldmann** [comment]
this isn't done, why did you close it?

**Comment by ThomasWaldmann** [comment]
https://github.com/pypa/python-packaging-user-guide/issues/320 see there for some links to blog posts and discussion.
