### ISSUE TITLE
Provide a link to an argument from the HTML to the API interface

### ISSUE THREAD

**Issue by wodny** [arguman/arguman.org#309]
Currently one has to use the http://en.arguman.org/api/v1/arguments/?search API or scrape the tree view code to find the argument's ID. Furthermore the search API does not allow to use the slug as the search term.

Example:
http://en.arguman.org/vim-is-better-than-emacs does not provide a link to http://en.arguman.org/api/v1/arguments/2286/.
One will not find this argument using a http://en.arguman.org/api/v1/arguments/?search=vim-is-better-than-emacs query.

**Comment by bahattincinic** [comment]
Thanks for your report. I've fixed your report. You can check #315
