### ISSUE TITLE
Add locate subdomains cross origin

### ISSUE THREAD

**Issue by om3rcitak** [arguman/arguman.org#313]
https://gist.github.com/barrabinfc/426829

**Comment by mmetince** [comment]
I believe we don't have to focus on cross-domain XHR request. We just need to set cookie with proper domain scope. Such as;

```SESSION_COOKIE_DOMAIN = '.arguman.org'```

If there is a different instance for each subdomain, all django instances have to use same (shared) secret key.

**Comment by fatiherikli** [comment]
I agree with @mmetince. Cookie domain configuration should resolve this problem.

**Comment by fatiherikli** [comment]
I just set the value on the production environment. It seems working fine.

**Comment by mmetince** [comment]
Cool! @fatiherikli . you'r too lazy to add 2 .dev domain into your hosts file, update your settings.py and test it in your local, aren't  you ? haha.

**Comment by fatiherikli** [comment]
Actually I have development environment for domain server like en.localhost, tr.localhost, but I was in working hours and I had no chance to switch that environment :') @mmetince
