### ISSUE TITLE
Redirect issue

### ISSUE THREAD

**Issue by abhishekshankar** [arguman/arguman.org#322]
When i create a new argument, the argument page is created but the link is not opening.

http://en-us.139.59.37.175:8000/copying-things-makes-innovation-go-to-next-level-158507b56fd748d79d1063b111ee3d98

**Comment by abhishekshankar** [comment]
When a new argument is added the link doesnt open.

What is the issue.

http://en-us.139.59.37.175:8000/what-is-god-without-man

**Comment by KrzysztofMadejski** [comment]
Hi,

Is it still the problem? What error have you got?

**Comment by radhikavm** [comment]
Yes we are experiencing the same issue the site gets redirected to en.domainname.com through PREVENT_LANGUAGE_REDIRECTION = True. Any ideas to solve this?

**Comment by dogeisler** [comment]
I have the same issue! Inserting PREVENT_LANGUAGE_REDIRECTION = True doesnt solve my problem.

**Comment by dogeisler** [comment]
UPDATE: This fix worked for me: https://github.com/arguman/arguman.org/pull/300/files
