### ISSUE TITLE
Add Polish language version

### ISSUE THREAD

**Issue by KrzysztofMadejski** [arguman/arguman.org#328]
I will be working on that.

**Comment by fatiherikli** [comment]
🎉

**Comment by fatiherikli** [comment]
You can go over `locale` directory, all you need is copying a language folder and translating them.

**Comment by KrzysztofMadejski** [comment]
`python manage.py makemessages -l pl` for the standard way to do it (it gathers all the translations, also recently added) - to be added to docs

**Comment by KrzysztofMadejski** [comment]
@fatiherikli 

#: templates/auth/profile.html:56
Are msgid "Fallacy Reports" ones that user has sent or ones that he received?

**Comment by KrzysztofMadejski** [comment]
TODO
- [ ] Define supported languages in settings (enumerate available + provide default) rather than in code (templates/base.html:53)
- [ ] Don't force domain in language chooser. Allow to use subcatalogs rather than subdomain to ease development, ie. arguman.org/en rather than en.arguman.org
- [ ] msgid "Newsfeed seems empty." -> add  "Show all users activity." just after it

**Comment by fatiherikli** [comment]
That's cool, thank you @KrzysztofMadejski!

Will you create a pull request?

**Comment by KrzysztofMadejski** [comment]
Sure! Thanks for getting back to me.

I'm still working on the translations and other more general tweaks (mentioned in the separate issues).
