### ISSUE TITLE
No module named networkx

### ISSUE THREAD

**Issue by KrzysztofMadejski** [arguman/arguman.org#331]
Used:
- premises/management/commands/reports_to_gml.py:6
- profiles/views.py:10
- profiles/views.py:11

**Comment by KrzysztofMadejski** [comment]
Add `networkx==1.11` to `requirements.txt`

**Comment by fatiherikli** [comment]
https://github.com/arguman/arguman.org/commit/a1fd3917797e1e2eb479689e744e62bdb572c3f5

**Comment by KrzysztofMadejski** [comment]
That was fast! :P

**Comment by fatiherikli** [comment]
haha thanks! :)
