### ISSUE TITLE
MERONYM vs HYPONYM

### ISSUE THREAD

**Issue by KrzysztofMadejski** [arguman/arguman.org#332]
If it's different then translation strings should be different to catch nuances in other languages: https://github.com/arguman/arguman.org/blob/master/web/nouns/models.py#L196-L197

If it's the same, why to distinguish these two as two relations?

**Comment by fatiherikli** [comment]
This distinguish comes from WordNet and other semantic networks. They are different things in a semantic way but it's hard to express. They are very close to each other in natural languages.

https://www.wikiwand.com/en/Meronymy

**Comment by KrzysztofMadejski** [comment]
Thank you for this clarification!
