### ISSUE TITLE
Add redirection from http:// to https:// on arguman.org

### ISSUE THREAD

**Issue by KrzysztofMadejski** [arguman/arguman.org#336]
Now creating a https certificate is super-easy and free with https://certbot.eff.org/.

Let me know if you need help with setting that up. PS. Multiple domain are not supported so for each language a separate certificate is needed.

`./certbot-auto --cert-name arguman -d arguman.org -d en.arguman.org -d fr.arguman.org -d tr.arguman.org -d ch.arguman.org -d pl.arguman.org` should get it going

**Comment by fatiherikli** [comment]
Actually we have a certificate thanks to cloudflare, all we need to to is adding a redirection middleware on django. 

This should work for instance: https://en.arguman.org

**Comment by KrzysztofMadejski** [comment]
Cool! I've changed the title.

I'm doing it most often on the webserver configuration.
```
RewriteCond %{HTTPS} off 
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,R=permanent]
```
Should work if you have access to Apache.

**Comment by fatiherikli** [comment]
Make sense, you're right. Django middleware is not necessary in that case. We use Nginx instead of Apache but the configuration is not much different.

**Comment by iangilman** [comment]
I came here to report this (since my browser warned me that your registration form was insecure, and I knew to try HTTPS, but your average user may not), but since it's already reported,  I'm just bumping the thread. :-)

**Comment by iangilman** [comment]
Is this fixed now? It doesn't seem to be, but maybe the fix hasn't been deployed yet?

**Comment by fatiherikli** [comment]
Hey @iangilman 

Can you send me a reproduction url? I need to check what is wrong. It's configuration my CloudFlare. I don't do anything on server side except signing the certificates.

**Comment by iangilman** [comment]
Apologies for the delayed response! Anyway, if I go here:

http://en.arguman.org/login/

It doesn't automatically forward me to the HTTPS version of that page, which it should. Tested just now on Mac Firefox.

**Comment by fatiherikli** [comment]
Got it, thanks! I'll fix that soon, mate :)

**Comment by iangilman** [comment]
Awesome. I love the site! :-)

**Comment by fatiherikli** [comment]
This is done!

**Comment by fatiherikli** [comment]
Try: http://en.arguman.org

**Comment by iangilman** [comment]
Beautiful, looks good! Thank you :-)
