### ISSUE TITLE
Önermeler bulunduğu elementin dışına taşabiliyor

### ISSUE THREAD

**Issue by demirhancosku** [arguman/arguman.org#34]
```
word-wrap: break-word;
```

Bu sorunu çözecektir.

**Comment by bbilginn** [comment]
https://tr.arguman.org/bilim-ve-sanat-nadiren-ortak-kategoride-bulusabilir

<img width="436" alt="image" src="https://user-images.githubusercontent.com/2061337/49203773-8d023980-f3ba-11e8-9197-a4170fbcb50e.png">

`#app .premise .premise-content: {word-wrap: break-word;}`

<img width="386" alt="image" src="https://user-images.githubusercontent.com/2061337/49203921-174a9d80-f3bb-11e8-90fa-f5d25235519e.png">
