### ISSUE TITLE
Allow Arguman country version to be hosted as an independent website

### ISSUE THREAD

**Issue by KrzysztofMadejski** [arguman/arguman.org#340]
Now arguman.org is practically a different websites for each language (because of the native content). I see an advantage of that for those who are not able to configure and host website themselves.

Planning to run Arguman in Poland, I'm thinking it would make the most sense if we were able to create a local context narrative around it, unique Polish sounding codename, host it under a different domain, etc.

I wonder if anyone else has this requirement as well? 
@fatiherikli what do you think about it?

----

So far I see that below changes are needed to support it:
- be able to easily disable middleware responsible for language choosing [maybe it's there just to document]
- extract Arguman.org domain from translation files and use `BASE_DOMAIN` setting - #333 
- allow to upload logo / or define a unique name
- "settingify" contact means:
  - twitter
  - reddit
  - email

**Comment by fatiherikli** [comment]
Yes, this abstraction is required to make different instances. People used to fork arguman's repository and make customizations there. 

What are you planning to do about Arguman in Poland? Having a different domain and repository makes sense in your case.

**Comment by KrzysztofMadejski** [comment]
Get some stakeholders that could be interested in using Arguman in their own projects or for their communities - unis, think tanks, non-profits.

Getting own branding is still in a plan phase, but I wanted to check first how do you feel about it.

Would you be open there to link Polish portal as an external independent link?
