### ISSUE TITLE
"Institution" misspelled on the "new argument page" 

### ISSUE THREAD

**Issue by haydenbetts** [arguman/arguman.org#358]
From the page http://en.arguman.org/new-argument
<img width="811" alt="screen shot 2017-08-12 at 6 04 45 pm" src="https://user-images.githubusercontent.com/2898213/29245236-d3788754-7f88-11e7-9ab4-8506dc5ff292.png">

**Comment by KrzysztofMadejski** [comment]
I've seen it, I want to tackle it in #339

**Comment by sjgknight** [comment]
I just made a bunch of edits to the English (including correcting this) in a fork https://github.com/uts-cic/arguman.org/commit/e9330e49dc7117ed5b1f586d40d5a42a667756d1 The edits corrected a few grammatical/spelling issues, and also tried to clarify some things a little more.
