### ISSUE TITLE
License issue: Switching GPL v3 to AGPL v3

### ISSUE THREAD

**Issue by ooguz** [arguman/arguman.org#383]
Hello,

Project's license is GNU GPL v3 now. GNU GPL is the best license for free software, except web applications. 

Arguman as a software running on web (server-side), the most appropriate license for Arguman is GNU AGPL v3 (or later). Because AGPL v3 is including some additional terms about softwares running on computer-network.

**Comment by fatiherikli** [comment]
bir version bump yapayım dedim, yeşillenmiş burası baya :)

**Comment by ooguz** [comment]
There are several BSD licenses such as Simplified BSD License, 4-clause BSD License or 3-clause BSD License etc. First of all, we have to determine which one we are talking about.

BSD Licenses and their simulants have problems about conserving freedom. We call them as non-copyleft free software licenses. Before that, I think I should explain "copyleft" term.

Copyleft means conserving freedom as I said at the first sentence. If an output (output means any kind of human production here, e.g software, music, art, photo etc.) licensed with a copyleft license, the derivative works based on this output **have to** be free (**Free as in freedom**) as the original work. BSD Licenses or Expat/X11 License (erroneously people call this license as MIT License) don't have copyleft feature; so if you license your software with these licenses, a proprietary software developer can easily convert your software's license into a proprietary license or migrate your software into themselves software. Therefore, the software will be non-free, and also they use your code to grow their wallets and stealing people's freedom. With copylefted licenses, the derivatives of the work **must** licensed under the same license or another copyleft license. 

GNU GPL set the term "copyleft" at the very beginning of free software. On free software philosophy, the important topic is user's freedom. Richard M. Stallman thought that a free software should stay free, consequently users as well. 

But when we are talking about a web application, GNU GPL's copyleft can be insufficient. In GPL, you have to redistribute the source code with copies of software; but there comes a problem about web applications, because they are running on a server, not in our computers. GNU AGPL v3 was authored to solve this problem; if you run an AGPL'd software in a server (in other words if software is used over networks) you have to distribute the source code of it. 

But why we need this? I'll give an example on Arguman. With this license; if somebody fork Arguman and create a public Git repository, they must license their fork with the same license GPL v3 according to the conditions of it. But, if they add some extra code/features to Arguman and create a website called argument.cc or something like that, they don't have to distribute the source code. Because, they are running the software, **not you**. 

To resolve this problems, I **strongly recommend** to switch GNU AGPL v3 immediately. This license will protect our software from vultures of proprietarians. BSD Licenses or Expat/X11/MIT Licenses, generally non-copyleft licenses only strong non-free software and it's adherents. 

**Further reading:**

* [https://copyleft.org/]
* [https://www.gnu.org/philosophy/pragmatic.html]
* [https://www.gnu.org/philosophy/free-sw.html]
* [https://www.gnu.org/licenses/license-recommendations.html#server]

**Comment by fatiherikli** [comment]
Done
