### ISSUE TITLE
Argümanlara Örnek Alanının Eklenmesi

### ISSUE THREAD

**Issue by alpertokgoz** [arguman/arguman.org#76]
bir fikir.

--
kaynaklar:
Coca Cola ramazan reklamları
gönderen:
xxx

şeklinde bir node gördüm, oysa Coca Cola ramazan reklamları kaynak değil örnek kategorisinde verilebilirdi.

**Comment by hmert** [comment]
Arguman'ın şu anki hali bunun için yeterli sanırım.
