### ISSUE TITLE
[Öneri] - Detay sayfasında Kayıt ve Giriş Butonları

### ISSUE THREAD

**Issue by aliemre** [arguman/arguman.org#98]
Bir argümanın detayına girip birşeyler eklemek istediğimde sisteme giriş yapmadığımı farkettim. Fakat detay sayfasında giriş ve kayıt butoonları olmadığı için ana sayfaya gitmek durumunda kalınıyor. Detay sayfasına da ilgili linkler eklenebilir.

**Comment by hmert** [comment]
bd5a9157d237a0eea9e73e5d5130d3d211e0bb9a ile çözüldü. Canlı sisteme aktarıldığında problem kalmamış olacak.
